# Change these first
owner: Certegy-Payment-Solutions # Your GitHub organization or username
repo: upptime # The name of this repository

sites:
  - name: Cashline Tomcat - PROD
    url: https://certegycashline.com/
  - name: Cashline Java - PROD
    url: https://cashline.certegy.com/health
  - name: Cashline Tomcat - CCE
    url: https://cce.certegycashline.com/
  - name: Cashline Java - CCE
    url: https://cce.cashline.certegy.com/health
  - name: Cashline Tomcat - UAT
    url: https://uat.certegycashline.com/
  - name: Cashline Java - UAT
    url: https://uat.cashline.certegy.com/health
  - name: Cashline Tomcat - QA
    url: https://qat.certegycashline.com/
  - name: Cashline Java - QA
    url: https://qat.cashline.certegy.com/health
  - name: Cashline Tomcat - Dev
    url: https://dev.certegycashline.com/
  - name: Cashline Java - Dev
    url: https://dev.cashline.certegy.com/health
  - name: BNPL Consumer Portal - UAT
    url:  https://bnpl-consumer-portal-uat.certegy.com
  - name: BNPL Consumer Portal - DEV
    url:  https://bnpl-consumer-portal-dev.certegy.com
  - name: BNPL Consumer Portal - Prod
    url:  https://dashboard.certegy.com
  - name: Bankpay - Prod
    url:  https://bankpay.certegy.com/health
  - name: Bankpay - CCE
    url:  https://cce.bankpay.certegy.com/health
  - name: Bankpay - QA
    url:  https://qa.bankpay.certegy.com/health
  - name: Cashline Admin Portal - QAT
    url:  https://qat.cashlineadminportal.com/
  - name: Cashline Admin Portal - DEV
    url:  https://dev.cashlineadminportal.com/
  - name: Cashline Admin Portal - Prod
    url:  https://certegycashline.com/
  - name: AskCertegy - PROD
    url: https://ask.certegy.com
  - name: AskCertegy - CCE
    url: https://cce.askcertegy.com
  - name: AskCertegy - QA
    url: https://qa.askcertegy.com
  - name: AskCertegy - DEV
    url: https://dev.askcertegy.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Certegy System Status
  introTitle: "**Certegy System Status** - Real-time system monitoring"
  introMessage: This page provides real-time monitoring status for Certegy's critical systems and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Notifications configuration
notifications:
  # You can add various notification channels here
  # See https://upptime.js.org/docs/notifications
  issues:
    assignees: # Add GitHub usernames here for issue assignments
