# Change these first
owner: Certegy-Payment-Solutions # Your GitHub organization or username
repo: upptime # The name of this repository

sites:
  # CoreWebService (SOAP V1)
#   - name: CoreWebService (SOAP V1) - CCE  # Disabled - Needs additional configuration
#     url: https://cce-soap-retail.certegy.com/v1
#     mtls: true
#   - name: CoreWebService (SOAP V1) - PROD  # Disabled - Needs additional configuration
#     url: https://soap-retail.certegy.com/v1
#     mtls: true

  # CoreWebService (SOAP V2)
#   - name: CoreWebService (SOAP V2) - CCE  # Disabled - Needs additional configuration
#     url: https://cce-soap-retail.certegy.com/v2
#     mtls: true
#   - name: CoreWebService (SOAP V2) - PROD  # Disabled - Needs additional configuration
#     url: https://soap-retail.certegy.com/v2
#     mtls: true

  # PCAWebService (SOAP)
#   - name: PCAWebService (SOAP) - CCE  # Disabled - Needs additional configuration
#     url: https://cce-soap-ccd.certegy.com/v1
#     mtls: true
#   - name: PCAWebService (SOAP) - PROD  # Disabled - Needs additional configuration
#     url: https://soap-ccd.certegy.com/v1
#     mtls: true

  # MICR_parser (SOAP)
#   - name: MICR_parser (SOAP) - CCE  # Disabled - Needs additional configuration
#     url: https://cce-soap-micr-parser.certegy.com/v1
#     mtls: true
#   - name: MICR_parser (SOAP) - PROD  # Disabled - Needs additional configuration
#     url: https://soap-micr-parser.certegy.com/v1
#     mtls: true

  # POSIPGateway Service (HTTPS)
#   - name: POSIPGateway Service (HTTPS) - CCE  # Disabled - Needs additional configuration
#     url: https://cce-pos-ip-gateway.certegy.com/v1
#     mtls: true
#   - name: POSIPGateway Service (HTTPS) - PROD  # Disabled - Needs additional configuration
#     url: https://pos-ip-gateway.certegy.com/v1
#     mtls: true

  # ReqEServiceSoap (SOAP)
#   - name: ReqEServiceSoap (SOAP) - CCE  # Disabled - Needs additional configuration
#     url: https://cce-soap-rege.certegy.com/v1
#     mtls: true
#   - name: ReqEServiceSoap (SOAP) - PROD  # Disabled - Needs additional configuration
#     url: https://soap-reqe.certegy.com/v1
#     mtls: true

  # PayNetLevel1
#   - name: PayNetLevel1 - CCE  # Disabled - Needs additional configuration
#     url: https://cce-paynet.certegy.com/PayNet/
#     mtls: true
#   - name: PayNetLevel1 - PROD  # Disabled - Needs additional configuration
#     url: https://paynet.certegy.com/PayNet/
#     mtls: true

  # PaynetMerchant
  - name: PaynetMerchant - CCE
    url: https://cce-merchant-app.certegy.com/portal-app/
    mtls: true
  - name: PaynetMerchant - PROD
    url: https://merchant-app.certegy.com/portal-app/
    mtls: true

  # kftool-certegy
  - name: kftool-certegy - CCE
    url: https://cce-kftool.certegy.com/kftool-certegy/
    mtls: true
  - name: kftool-certegy - PROD
    url: https://kftool.certegy.com/kftool-certegy/
    mtls: true

  # Edoc
#   - name: Edoc - CCE  # Disabled - Needs additional configuration
#     url: https://cce-edoc.certegy.com
#     mtls: true
#   - name: Edoc - PROD  # Disabled - Needs additional configuration
#     url: https://edoc.certegy.com
#     mtls: true

  # ask-certegy
  - name: ask-certegy - CCE
    url: https://cce.askcertegy.com
    mtls: true
  - name: ask-certegy - PROD
    url: https://askcertegy.com
    mtls: true

  # Consumer Portal
  - name: Consumer Portal - PROD
    url: https://dashboard.certegy.com
    mtls: true

  # CoreWebService (JSON)
#   - name: CoreWebService (JSON) - CCE  # Disabled - Needs additional configuration
#     url: https://cce.retail.certegy.com/v1
#     mtls: true
#   - name: CoreWebService (JSON) - PROD  # Disabled - Needs additional configuration
#     url: https://retail.certegy.com/v1
#     mtls: true

  # IVR
#   - name: IVR - CCE  # Disabled - Needs additional configuration
#     url: https://cce.ivr.certegy.com/v1/micr-validation
#     mtls: true
#   - name: IVR - PROD  # Disabled - Needs additional configuration
#     url: https://ivr.certegy.com/v1/micr-validation
#     mtls: true

  # Automated Client Onboarding (HTTP)
#   - name: Automated Client Onboarding (HTTP) - CCE  # Disabled - Needs additional configuration
#     url: https://cce.onboarding.certegy.com/v1
#     mtls: true
#   - name: Automated Client Onboarding (HTTP) - PROD  # Disabled - Needs additional configuration
#     url: https://onboarding.certegy.com/v1
#     mtls: true

  # Cashline services
  - name: Cashline Tomcat - CCE
    url: https://cce.certegycashline.com/
    mtls: true
  - name: Cashline Tomcat - PROD
    url: https://certegycashline.com/
    mtls: true

  - name: Cashline Java - CCE
    url: https://cce.cashline.certegy.com/health
    mtls: true
  - name: Cashline Java - PROD
    url: https://cashline.certegy.com/health
    mtls: true

  # Cashline Admin Portal
  - name: Cashline Admin Portal - CCE
    url: https://cce.cashlineadminportal.com/
    mtls: true
  - name: Cashline Admin Portal - PROD
    url: https://cashlineadminportal.com/
    mtls: true

  # Bankpay
  - name: Bankpay - CCE
    url: https://cce.bankpay.certegy.com/health
    headers:
      - "Authorization: Basic $BANKPAY_AUTH_TOKEN"
  - name: Bankpay - PROD
    url: https://bankpay.certegy.com/health
    headers:
      - "Authorization: Basic $BANKPAY_AUTH_TOKEN"
