name: mTLS Check
on:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [mtls-check]
  workflow_dispatch:

jobs:
  check-mtls-endpoints:
    name: Check mTLS Endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install js-yaml
      
      - name: Check mTLS endpoints
        run: |
          node scripts/check-mtls-endpoints.js
        env:
          MTLS_CERTIFICATE: ${{ secrets.MTLS_CERTIFICATE }}
          MTLS_CERTIFICATE_PASSWORD: ${{ secrets.MTLS_CERTIFICATE_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
